= CONTRIBUTING
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:uri-oracle-oca: :uri-oracle-oca: https://oca.opensource.oracle.com/
:imagesdir: docs/diagrams
:toc:

Oracle welcomes contributions to this repository from anyone.

If you want to submit a pull request to fix a bug or enhance an existing feature, please first open an issue and link to that issue when you submit your pull request.

If you have any questions about a possible submission, feel free to open an issue too.

== Coding conventions

Be sure to check xref:docs/codingconventions.adoc[the coding conventions] of this project before starting to develop.

== Required documentation updates

The documentation for your contribution is as valuable as the code you contribute.

Please ensure the documentation is updated to include any new feature, functionality or fix you contribute. Including documentation changes will make the contribution process far quicker and easier (and the maintainers will love you!).

You should ensure that your documentation changes include the following:

* Update xref:CHANGELOG.adoc[CHANGELOG] under the 'Unreleased' section. The maintainers will include this to the appropriate version section during the release process for that version
* If your contribution provision new resources, update the README introduction section
* Add your GitHub handler to xref:CONTRIBUTORS.adoc[CONTRIBUTORS] under the *CONTRIBUTORS* section
* Don't forget how important the documentation is, especially for examples: we would love it if you updated the `main.tf` and `variables.tf` in the `examples/` folder. A simple example is fine.
* You should also update the code examples in link:examples/README.md[examples/README]: it contains sample code blocks that probably needs to be updated to reflect your changes

NOTE: Tables on xref:docs/terraformoptions.adoc[docs/terraformoptions] are automatically generated using terraform-docs. The maintainer will refesh this document before release, but variables must be defined as described in xref:doc/codingconventions.adoc[docs/codingconventions].

== How to contribute to this repository

Pull requests can be made under
{uri-oracle-oca}[The Oracle Contributor Agreement (OCA)].

For pull requests to be accepted, the bottom of your commit message must have
the following line using your name and e-mail address as it appears in the
OCA Signatories list.

----
Signed-off-by: Your Name <you@example.org>
----

This can be automatically added to pull requests by committing with:

----
  git commit --signoff
----

or by turning on the "Always Sign Off" flag in your IDE's preferences.

Only pull requests from committers that can be verified as having signed the OCA can be accepted.

== Pull request process

* Fork this repository
* Create a branch in your fork to implement the changes. We recommend using the issue number as part of your branch name, e.g. `1234-fixes`
* Ensure that any documentation is updated with the changes that are required by your fix.
* Ensure that any samples are updated to reflect your new features.
* Submit your pull request to the `Dev` branch. **Do not leave the pull request description blank**. Explain exactly what your changes are meant to do and provide simple steps on how to validate your changes. Ensure that you reference the issue you created as well adding `#1234` to the description.

We will assign the pull request to reviewers before it is merged. Please engage with the maintainer if there is a clarification request and change suggestion. Pull Request with no follow-up from the creator will be closed.

The sequence diagram below represents the git flow we follow for contribution.

image::How to submit your contribution.svg[]
