= Pre-requisites
:idprefix:
:idseparator: -
:sectlinks:
:toc:
:toc-placement!:

:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-compute-instance
:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master
:uri-docs: {uri-rel-file-base}/docs

:uri-oci: https://cloud.oracle.com/cloud-infrastructure
:uri-oci-compartment: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingcompartments.htm#two
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-documentation: https://docs.cloud.oracle.com/iaas/Content/home.htm
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#two
:uri-terraform: https://www.terraform.io
:uri-terraform-download: https://www.terraform.io/downloads.html
:uri-hashicorp-brew-tap-announcement: https://www.hashicorp.com/blog/announcing-hashicorp-homebrew-tap

This section will guide you through the pre-requisites before you can use this project.

You can proceed to the xref:docs/quickstart.adoc[Quick Start guide] if you have already done these steps.

toc::[]

== Install Terraform

Start by installing Terraform and configuring your path.

=== Installing Terraform on Oracle Linux

If you are using Oracle Linux, you can install Terraform as follows:

[source,bash]
----
yum -y install oraclelinux-developer-release-el7 && yum -y install terraform
----

=== Installing Terraform on macOS

If you are using a Mac, you can install Terraform as follows:

[source,bash]
----
brew install hashicorp/tap/terraform
----

This will install Terraform using the official Hashicorp homebrew tap. For more details between the differences and benefits to use the community maintained or the official homebrew tap, see {uri-hashicorp-brew-tap-announcement}[Hashicorp's announcement]

=== Manual Installation

If you prefer to install Terraform manually, you can follow these instructions:

. Open your browser and navigate to the {uri-terraform-download}[Terraform download page]. You need version 0.12.24+.

. Download the appropriate version for your operating system.

. Extract the the contents of compressed file and copy the terraform binary to a location that is in your path (see next section below).

. You will also need to configure your path.

==== Configure path on Linux/macOS

Open a terminal and type the following:

[source,bash]
----
sudo mv /path/to/terraform /usr/local/bin
----

==== Configure path on Windows
Follow the steps below to configure your path on Windows:

. Click on 'Start', type 'Control Panel' and open it
. Select System > Advanced System Settings > Environment Variables
. Select System variables > PATH and click 'Edit'
. Click New and paste the location of the directory where you have extracted the terraform.exe
. Close all open windows by clicking 'OK'
. Open a new terminal and verify terraform has been properly installed

=== Testing Terraform installation

Open a terminal type this command:

[source,bash]
----
> terraform -v
----

The first line of the output should be `Terraform vX.X.X` with your installed version.
You will also see below any provider that is accessible to Terraform in the current folder.

== Generate and upload your OCI API keys

Follow the documentation for {uri-oci-keys}[generating and uploading your api keys].

Note the key fingerprint.

== Create an OCI compartment

Follow the documentation for {uri-oci-compartment}[creating a compartment].

== Obtain the necessary OCIDs

The following OCIDs are required:

. Compartment OCID
. Tenancy OCID
. User OCID

Follow the documentation for {uri-oci-ocids}[obtaining the tenancy and user ocids].

To obtain the compartment OCID:

1. Navigate to Identity > Compartments
2. Click on your Compartment
3. Locate OCID on the page and click on `Copy`
